### ISSUE TITLE
Introduction of firework.css in AI on the edge firmware appears to have broken collectmeterdigits

### ISSUE THREAD

**Issue by ashdriver** [haverland/collectmeterdigits#12]
Since upgrading AI on the edge firmware to rev 14, collecting images results in the error: 

Traceback (most recent call last):
  File "collectmeterdigits\__main__.py", line 39, in <module>
    main()
  File "collectmeterdigits\__main__.py", line 34, in main
    collect(args.collect, args.days, keepolddata=args.keepdownloads, download=not args.nodownload, startlabel=args.startlabel)
  File "collectmeterdigits\collect.py", line 193, in collect
    readimages(meter, target_raw_path, days)
  File "collectmeterdigits\collect.py", line 69, in readimages
    img = Image.open(requests.get(serverurl+url, stream=True).raw)
  File "PIL\Image.py", line 3147, in open
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002F32624E270>
[99400] Failed to execute script '__main__' due to unhandled exception!

By filtering the list of urls in collect.py for only those ending in jpg I have avoided this issue, it appeared to by interpreting firework.css as an image file.

**Comment by haverland** [comment]
Fixed with v1.0.3
